#!/bin/bash

timeout_flag=
usage() { echo "Usage: $0 [-t <integer>]" 1>&2; exit 1; }

while getopts t: OPT; do
    case $OPT in
        t )         timeout_flag="-t $OPTARG"
                    ;;
        * )         usage
                    exit 1
   esac
   shift
done

docker-compose -f cmds/bootstrap/docker-compose.yml down $timeout_flag
